language: csharp

solution: MarketPlaceBackend.sln

notifications:

  email:

    on_success: always

    on_failure: always

  slack: srboeingdotnet:pZz5KfrgntyjLpS9a1d2b1rH

mono: none

dotnet: 2.1

script:

  - dotnet restore MarketPlace/MarketPlace.csproj
  - dotnet restore MarketPlace.Tests/MarketPlace.Tests.csproj
  - dotnet test MarketPlaceBackend.Tests