swagger: "2.0"
info:
  title: Chat Microservices
  description: All the APIs provided by the chat team
  version: 0.0.1
definitions:
  
  channel:
    type: object
    properties:
      channelId:
        type: integer
      channelName:
        type: string
      users:
        type: array
        items:
          $ref: "#/definitions/user"
      admin:
        $ref: "#/definitions/user"
      messages:
        type: array
        items: 
          $ref: "#/definitions/message"
  
  user:
    type: object
    required:
      - username
      - password
    properties:
      userId:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      username: 
        type: string
        format: email
      designation:
        type: string
      workspaceName:
        type: string
  
  message: 
    type: object
    properties:
      messageId:
        type: integer
      messageBody:
        type: string
      timeStamp:
        type: string
        format: date-time
      isStarred:
        type: boolean
      sender:
        $ref: "#/definitions/user"
  
  workspace:
    type: object
    required:
      - workspaceId
      - workspaceName
    properties:
      workspaceId:
        type: integer
      workspaceName:
        type: string
      channels: 
        type: array
        items:
          $ref : "#definitions/channel"
paths:
  /member:
    post:
      summary: Adds a member to a channel
      parameters:
      - name: userName
        in: query
        required: true
        schema:
          type: string
          format: email
      - name: channelId
        in: query
        required: true
        schema:
          type: integer
      responses:
        201:
          description: User added
        404:
          description: User not added

    delete:
      summary: Remove a member from a channel
      parameters:
      - name: userName
        in: query
        required: true
        schema:
          type: string
          format: email
      - name: channelId
        in: query
        required: true
        schema:
          type: integer
      responses:
        200:
          description: User removed
        404:
          description: User not found    
       

  /channels:
    get:
      summary: Returns list of channels the user is part of
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          description: userId (email)
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
          description: workspace name
      responses:
        200:
          description: List of channels
          schema:
            type: array
            items:
              type: object
              properties:
                channelId:
                  type: integer
                channelName:
                  type: string
                users:
                  type: array
                  items:
                    $ref: "#/definitions/user"
                admin:
                    $ref: "#/definitions/user"
                messages:
                  type: array
                  items: 
                    $ref: "#/definitions/message"
                # $ref: "#/definitions/Channels"
    
    delete:
      summary: Delete a channel from a workspace
      parameters:
        - in: query
          name: channelId
          required: true
          schema:
            type: integer
          description: channel id
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
          description: workspace name
      responses:
        200:
          description: Channel removed
        404:
          description: Channel not found
    
    post:
      summary: Adds a channel to a workspace
      parameters:
      - in: query
        name: channelId
        required: true
        schema:
          type: integer
      - in: query
        name: worspaceName
        required: true
        schema:
          type: string
      responses:
        201:
          description: Channel is added
        404:
          description: Channel not added

  /channels/messages:
    get:
      summary: Returns list of messages in a channel
      parameters:
      - in: query
        name: channelId
        required: true
        schema:
          type: integer
      - in: query
        name: worspaceName
        required: true
        schema:
          type: string
      responses:
        200:
          description: List of messages
          schema:
            type: array
            items:
              $ref: "#/definitions/message"
        404:
          description: Channel/Workspace not found
      
    delete:
        summary: Delete a message from a channel
        parameters:
        - in: query
          name: channelId
          required: true
          schema:
            type: integer
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
        - in: query
          name: messageId
          required: true
          schema:
            type: integer
        responses:
          200:
            description: Message deleted
          404:
            description: Message not found
          
  /users:
    get:
      summary: Returns list of all users in a workspace
      parameters:
        - in: query
          name: worspaceName
          schema:
            type: string
          description: workspace name
      responses:
        200:
          description: List of users
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        404:
          description: Workspace not found

    post:
      summary: Adds a user to a workspace
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: integer
      - in: query
        name: worspaceName
        required: true
        schema:
          type: string
      responses:
        201:
          description: User is added
        404:
          description: User not added

    delete:
      summary: Delete a user from a workspace
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
          description: user id
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
          description: workspace name
      responses:
        200:
          description: User removed
        404:
          description: user not found
    
    put:
      summary: Update user details in a workspace
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
          description: user id
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
          description: workspace name
        - in: body
          name: body
          description: Updated user object
          schema:
            $ref: "#/definitions/user"
      responses:
        200:
          description: User updated
          schema:
            items:
              $ref: "#/definitions/user"
        404:
          description: user not found

  /workspaces:
    get:
      summary: Returns list of all workspaces if no parameter given or by worksapce name
      parameters:
      - in: query
        name: worspaceName
        required: true
        schema:
          type: string
      description: workspace name
      responses:
        200:
          description: List of workspaces
          schema:
            type: array
            items:
              $ref: "#/definitions/workspace"
        404:
          description: Workspace not found

    delete:
      summary: Delete a workspace
      parameters:
        - in: query
          name: worspaceName
          required: true
          schema:
            type: string
          description: workspace name
      responses:
        200:
          description: Workspace removed
        404:
          description: workspace not found
    
    post:
      summary: Create a new workspace
      parameters:
      - in: body
        name: body
        description: Workspace object
        schema:
          $ref: "#/definitions/workspace"
      responses:
        201:
          description: Workspace is created
        404:
          description: Workspace not created



                 
                
                   

 