version: '3.4'

services:
 web:
   build: .
     # context: .
     #   dockerfile: dockerfile

   ports:
       - "9999:80"
   depends_on:
       - db
 db:
   image: "microsoft/mssql-server-linux"
   environment:
     SA_PASSWORD: "Anashku@100"
     ACCEPT_EULA: "Y"