
version: "3"
services:
  web:
    build: .
    container_name: RTM
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

